CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS tasks(
    id SERIAL PRIMARY KEY,
    id_user INTEGER,
    name VARCHAR(255) NOT NUll UNIQUE,
    description VARCHAR(255) NOT NULL,
    lvl INTEGER NOT NULL
);
